# theme
source = ~/.cache/wal/hyprtheme.conf
source = ~/.cache/wallpaper.conf

# variables
source = ~/.config/hypr/hyprvars.conf

# autostart
source = ~/.config/hypr/hyprstart.conf

# environment variables
source = ~/.config/hypr/hyprenv.conf

# key bindings
source = ~/.config/hypr/hyprkeys.conf

#####################
### LOOK AND FEEL ###
#####################
decoration {
    rounding = 8
    active_opacity = 0.97
    inactive_opacity = 0.85
    fullscreen_opacity = 1.0
    
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = false
        noise = 0.0117
        contrast = 1.2
        brightness = 1.0
        vibrancy = 0.1696
        vibrancy_darkness = 0.85
        special = false
        new_optimizations = true
    }
}

animations {
    enabled = false
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1
    bezier = overshot, 0.4, 0.8, 0.2, 1.2
    bezier = fluent, 0.4, 0, 0.2, 1
    
    animation = windows, 1, 5, overshot, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = windowsMove, 1, 4, fluent
    animation = border, 1, 6, fluent
    animation = borderangle, 1, 6, fluent
    animation = fade, 1, 6, fluent
    animation = workspaces, 1, 5, fluent, slidevert
    animation = specialWorkspace, 1, 5, smoothIn, slidevert
    animation = layers, 1, 5, fluent
}

general {
    border_size = 2
    # col.active_border = rgba(7FB4CAAA) rgba(957FB8AA) 45deg

    # col.active_border = rgba(42A6A6FF) # cyan
    # col.inactive_border = rgba(1F1F2866)

    col.active_border = rgb($color4)
    col.inactive_border = rgb($color0)
    
    gaps_in = 4
    gaps_out = 8
    resize_on_border = true
    extend_border_grab_area = 15
}

dwindle {
    pseudotile = yes
    preserve_split = yes
    force_split = 2
    smart_split = no
    special_scale_factor = 0.95
}

master {
    new_on_top = true
    orientation = left
    inherit_fullscreen = true
    mfact = 0.55
}

input {
    follow_mouse = 1
    float_switch_override_focus = 0
    sensitivity = -0.5
    touchpad {
        natural_scroll = yes
        disable_while_typing = true
    }
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    force_default_wallpaper = 0
    animate_manual_resizes = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
}

#############
### INPUT ###
#############
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 

    touchpad {
        natural_scroll = false
    }
}

# gestures {
#     workspace_swipe = true
# }

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

## Monitor
monitor=DP-1,1920x1080@60,auto,1

##############################
### WINDOWS AND WORKSPACES ###
##############################
# windowrulev2 = workspace 2, ^(firefox-nightly)$
windowrulev2 = workspace 2, class:^(zen)
windowrulev2 = workspace special:magic, class:^(Spotify)$
windowrulev2 = float,class:^(qalculate-gtk)$,title:^(Qalculate!)$
windowrulev2 = size 80% 80%,class:^(qalculate-gtk)$,title:^(Qalculate!)$
windowrulev2 = float,class:^(pavucontrol-qt)$,title:^(Volume Control)$
windowrulev2 = size 45% 50%,class:^(pavucontrol-qt)$,title:^(Volume Control)$
windowrulev2 = float,class:^(blueman-manager)$,title:^(Bluetooth Devices)$
windowrulev2 = size 45% 50%,class:^(blueman-manager)$,title:^(Bluetooth Devices)$
windowrulev2 = float,class:^(nm-connection-editor)$,title:^(Network Connections)$
windowrulev2 = size 45% 50%,class:^(nm-connection-editor)$,title:^(Network Connections)$



